global:
  scrape_interval: 15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 15s
    
scrape_configs:
  - job_name: 'linked-business-metrics'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['host.docker.internal:44330']
